name: Run git_data_fetcher

on:
    push:
    schedule:
        - cron: '0 0 * * SUN'

jobs:
    run-script-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '12'

        - name: Install dependencies
          run: npm install

        - name: Run script
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_USERNAME: ${{ github.actor }}
          run: node git_data_fetcher.mjs

        - name: Commit and push if it changed
          run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add -A
            git diff --quiet && git diff --staged --quiet || git commit -m "Update data"
            git push
    deploy:
        needs: run-script-and-push
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
    
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '12'
    
        - name: Install dependencies
          run: npm install
    
        - name: Run deploy
          run: npm run deploy